version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
        - "${DB_MYSQL_PORT}:3306"

  adminer:
      image: adminer
      depends_on:
          - mysql
      ports:
          - "8080:8080"
