version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
        - "${DB_MYSQL_PORT}:3306"

  postgres:
    image: postgres
    environment:
        - POSTGRES_USER=${DB_POSTGRES_USERNAME}
        - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
        - POSTGRES_DB=${DB_POSTGRES_DATABASE}
    ports:
        - "${DB_POSTGRES_PORT}:5432"
    volumes: 
        - ./init-p/01.sql:/docker-entrypoint-initdb.d/01.sql

  adminer:
      image: adminer
      depends_on:
          - mysql
      ports:
          - "8080:8080"
