name: Test MySQL Connection

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start MySQL
        uses: docker://docker:19.03.13
        with:
          args: up -d mysql
      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h"$MYSQL_HOST" --silent; do
            sleep 1
          done
      - name: Run Tests
        run: go test
