name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
         go-version: 1.12
      - name: Build the stack
        run: docker-compose up -d
      - name: Run Setup
        run: make setup 
      - name: Run tests
        run: make test
