name: Test MySQL Connection

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start MySQL Service
        uses: docker/compose-action@v1
        with:
          # Start the MySQL service defined in the `docker-compose.yml` file
          command: up mysql
          # Specify the path to the `docker-compose.yml` file
          file: docker-compose.yml
