name: Test MySQL Connection

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start LocalStack
        uses: localstack/actions/localstack@v1
        with:
          services: mysql
      - name: Set Environment Variables
        run: |
          echo "::set-env name=DB_MYSQL_USERNAME::root"
          echo "::set-env name=DB_MYSQL_PASSWORD::root"
          echo "::set-env name=DB_MYSQL_PORT::3306"
          echo "::set-env name=DB_MYSQL_HOST::localhost"
          echo "::set-env name=DB_MYSQL_DATABASE::todo"
      - name: Run Tests
        run: make test
